"""Generate the harness adapters from scripts/harness/adapters.py.

uv run just harness-sync    → write/update the generated files (and delete obsolete ones)
uv run just harness-check   → fail if any of them differs from its source (in `just check`)
"""

from __future__ import annotations

import sys
from pathlib import Path

from harness.adapters import AGENTS, SKILLS, Agent, CodexProfile, Skill

ROOT = Path(__file__).resolve().parents[2]
MARKER = "GENERATED by scripts/harness/sync.py"
NOTICE = (
    f"{MARKER} — do not edit. Source: scripts/harness/adapters.py + docs/harness/roles/. "
    "Run `uv run just harness-sync`."
)

# Directories that hold generated files (to detect obsolete ones).
GENERATED_ROOTS = (".claude/agents", ".claude/skills", ".codex/agents", ".agents/skills")


def wrap(text: str, width: int) -> list[str]:
    lines: list[str] = []
    line = ""
    for word in text.split():
        if line and len(line) + len(word) + 1 > width:
            lines.append(line)
            line = word
        else:
            line = f"{line} {word}" if line else word
    if line:
        lines.append(line)
    return lines


def yaml_block(text: str) -> str:
    return ">\n" + "\n".join(f"  {line}" for line in wrap(text, 88))


def claude_agent(agent: Agent) -> str:
    tools = f"\ntools: {agent['claude_tools']}" if agent.get("claude_tools") else ""
    return (
        f"---\nname: {agent['name']}\ndescription: {yaml_block(agent['description'])}\n"
        f"model: {agent['claude_model']}{tools}\n---\n\n<!-- {NOTICE} -->\n\n{agent['body']}\n"
    )


def codex_profile(agent: Agent, profile: CodexProfile) -> str:
    instructions = f"{agent['body']}\n\nProfile note: {profile['note']}"
    description = "\n".join(wrap(agent["description"], 88))
    if "'''" in instructions or "'''" in description:
        raise ValueError(f"{profile['name']}: the body cannot contain '''")
    return (
        f"# {NOTICE}\n"
        f'name = "{profile["name"]}"\n'
        f'model = "{profile["model"]}"\n'
        f'model_reasoning_effort = "{profile["effort"]}"\n\n'
        f"description = '''\n{description}\n'''\n\n"
        f"developer_instructions = '''\n{instructions}\n'''\n"
    )


def skill(entry: Skill) -> str:
    return (
        f"---\nname: {entry['name']}\ndescription: {yaml_block(entry['description'])}\n---\n\n"
        f"<!-- {NOTICE} -->\n\n{entry['body']}\n"
    )


def build_outputs(agents: list[Agent] = AGENTS, skills: list[Skill] = SKILLS) -> dict[str, str]:
    outputs: dict[str, str] = {}
    for agent in agents:
        outputs[f".claude/agents/{agent['name']}.md"] = claude_agent(agent)
        for profile in agent["codex_profiles"]:
            outputs[f".codex/agents/{profile['name']}.toml"] = codex_profile(agent, profile)
    for entry in skills:
        outputs[f".claude/skills/{entry['name']}/SKILL.md"] = skill(entry)
        outputs[f".agents/skills/{entry['name']}/SKILL.md"] = skill(entry)
    return outputs


def existing_generated(root: Path) -> list[str]:
    """Existing files carrying the generated marker (candidates for obsolete)."""
    found: list[str] = []
    for top in GENERATED_ROOTS:
        base = root / top
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*")):
            if path.is_file() and not path.is_symlink() and MARKER in (_read(path) or ""):
                found.append(path.relative_to(root).as_posix())
    return found


def _read(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError, UnicodeDecodeError:
        return None


def sync(root: Path, outputs: dict[str, str], check: bool) -> list[str]:
    """Return the drift (`+` missing, `~` different, `-` obsolete); write it unless `check`."""
    drift: list[str] = []
    for rel, content in outputs.items():
        full = root / rel
        current = _read(full) if full.is_file() else None
        if current == content:
            continue
        drift.append(f"+ {rel}" if current is None else f"~ {rel}")
        if not check:
            full.parent.mkdir(parents=True, exist_ok=True)
            full.write_text(content, encoding="utf-8", newline="\n")
    for rel in existing_generated(root):
        if rel in outputs:
            continue
        drift.append(f"- {rel}")
        # Only deletes files it generated itself (they carry the marker).
        if not check:
            (root / rel).unlink()
    return drift


def main(argv: list[str] | None = None, root: Path = ROOT) -> int:
    args = sys.argv[1:] if argv is None else argv
    if any(arg != "--check" for arg in args):
        print("Usage: sync.py [--check]", file=sys.stderr)
        return 2
    check = "--check" in args
    outputs = build_outputs()
    drift = sync(root, outputs, check)
    if check and drift:
        print(
            "✖ harness-check — adapters out of date (run uv run just harness-sync):\n  "
            + "\n  ".join(drift),
            file=sys.stderr,
        )
        return 1
    if check:
        print(f"✔ harness-check — {len(outputs)} adapters up to date")
    else:
        changes = ", ".join(drift) if drift else "no changes"
        print(f"✔ harness-sync — {changes} ({len(outputs)} adapters)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
